name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-west-1
  AWS_GHA_ROLE: ${{ secrets.AWS_GHA_ROLE }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

jobs:
  build-n-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ env.AWS_GHA_ROLE }}
          role-session-name: gha-session
          aws-region: ${{ env.AWS_REGION }}
          mask-aws-account-id: true
      
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2
        with: 
          mask-password: true
      
      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.AWS_ECR_REPOSITORY_URL }}/backend:latest
      
      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.AWS_ECR_REPOSITORY_URL }}/frontend:latest
      
      - name: Update task definitions
        run: |
          sed -i "s/ACCOUNT_ID/${env.AWS_ACCOUNT_ID}/g" aws/backend-task-definition.json
          sed -i "s/ACCOUNT_ID/${env.AWS_ACCOUNT_ID}/g" aws/frontend-task-definition.json
      
      - name: Deploy backend service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: aws/backend-task-definition.json
          service: ${{ secrets.AWS_BACKEND_SERVICE_NAME }}
          cluster: ${{ secrets.AWS_ECS_CLUSTER_NAME }}
          region: ${{ env.AWS_REGION }}
          wait-for-service-stability: true
      
      - name: Deploy frontend service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: aws/frontend-task-definition.json
          service: ${{ secrets.AWS_FRONTEND_SERVICE_NAME }}
          cluster: ${{ secrets.AWS_ECS_CLUSTER_NAME }}
          region: ${{ env.AWS_REGION }}
          wait-for-service-stability: true